### ISSUE TITLE
pfcrypto fails to connect to alternative.me due to CORS policy

### ISSUE THREAD

**Issue by didyouexpectthat** [sclem/pfcrypto#17]
Went to my personalcapital today and noticed it hadn't been updating for some time. I pop open the console and see these:

- Access to fetch at 'https://api.alternative.me/v1/ticker/?limit=0' from origin 'https://home.personalcapital.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
- personalcapital.js:121 GET https://api.alternative.me/v1/ticker/?limit=0 net::ERR_FAILED
- personalcapital.js:327 Uncaught (in promise) TypeError: Failed to fetch

![image](https://user-images.githubusercontent.com/1329077/91627286-45338c00-e96b-11ea-8869-1fafa508a472.png)

Any suggestions?

**Comment by rahulparekh** [comment]
Facing the same issue

**Comment by egonzalezpozega** [comment]
I'm having the same issue

**Comment by 8pozzum** [comment]
Oddly enough, pfcrypto works fine on my chromebook that may or may not be up to date.  There is a workaround, but it may not be safe for a normal user so I'm not going to post it.

Something must have changed in chrome or the recent Windows update.

**Comment by sclem** [comment]
Issue is here:

https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

The extension now needs a background page to perform the requests to external APIs and then relay the info back to the content script with chrome's messaging API. The "internal" requests to personal capital should still work via the content script. Will be a bit of a refactor but shouldn't be too hard.

If someone is already working on this let me know, otherwise I might be able to knock it out over the weekend. I had to do this same thing for another extension already.

**Comment by sclem** [comment]
Should be fixed in the related PR. If someone else can verify the fix works for them, I'll push it to the webstore.

**Comment by didyouexpectthat** [comment]
Hi @sclem 
Tested #20 and all is back as expected.
![image](https://user-images.githubusercontent.com/1329077/94748088-59392780-0335-11eb-84d9-5f420849c540.png)

Thank you.
