### ISSUE TITLE
certain currencies not updating

### ISSUE THREAD

**Issue by ethangoldspiel** [sclem/pfcrypto#7]
0x and tron not updating. perhaps due to conflicts? TRON is updating as TORON Inc and 0x perhaps there is an issue as it is a zero, or two symbols?

**Comment by sclem** [comment]
You've found a bug for 0x, I'll fix it. For TRON, since it also matches a valid stock ticker, you'll have to make personal capital not find the holding in its own search. You can do this by appending any special characters to the beginning/end of the ticker name.

For example, `$TRON` would work or `TRON.MYWALLET` (It will read til the first dot).

**Comment by ethangoldspiel** [comment]
Thanks Spencer!
ᐧ

*Ethan Goldspiel*
